import 'media_source.dart';

const sourceCatalog = <MediaSource>[
  MediaSource(
    id: 'tbys',
    index: 0,
    name: '拖布影视',
    kind: SourceKind.movies,
    defaultDomain: 'https://www.rainvi.com',
    info: '存在广告，资源一般',
    health: SourceHealth.normal,
  ),
  MediaSource(
    id: 'silisili',
    index: 1,
    name: '嘶哩嘶哩',
    kind: SourceKind.anime,
    defaultDomain: 'https://www.sssfun.cc',
    info: '原项目依赖站点 Cookie 才能进入内容页',
    health: SourceHealth.abnormal,
    canSearch: true,
    rssPath: '/rss.xml',
    message: '按原 Java 版行为默认附带站点访问 Cookie；设置页可本地覆盖。',
  ),
  MediaSource(
    id: 'iyinghua',
    index: 2,
    name: '樱花动漫',
    kind: SourceKind.anime,
    defaultDomain: 'https://www.iyinghua.cc',
    info: '当前网页域名已从原项目 .com/.io 迁移到 .cc；搜索有验证码，暂不支持。',
    health: SourceHealth.normal,
    canSearch: false,
    message: '搜索页需要验证码，Flutter 版不做绕过；首页、分类、详情可用。',
  ),
  MediaSource(
    id: 'anfuns',
    index: 3,
    name: 'AnFuns',
    kind: SourceKind.anime,
    defaultDomain: 'https://www.anfuns.vip',
    info: '原项目标注站点已关闭',
    health: SourceHealth.shutdown,
    canSearch: false,
    message: '站点已关闭，保留结构但不发起请求。',
  ),
  MediaSource(
    id: 'libvio',
    index: 4,
    name: 'LIBVIO',
    kind: SourceKind.movies,
    defaultDomain: 'https://www.libvio.run',
    releasePage: 'https://ifabu.vip',
    info: '质量高，但可能存在域名变更或安全检测。',
    health: SourceHealth.normal,
  ),
  MediaSource(
    id: 'zxzj',
    index: 5,
    name: '在线之家',
    kind: SourceKind.movies,
    defaultDomain: 'https://www.zxzj.one',
    releasePage: 'https://zxzj.app',
    info: '热门电影/电视剧，无广告，可能存在域名变更或安全检测。',
    health: SourceHealth.normal,
  ),
  MediaSource(
    id: 'five_movie',
    index: 6,
    name: '555电影',
    kind: SourceKind.movies,
    defaultDomain: 'https://www.55i5m2t9p6.shop',
    releasePage: 'https://55s9q8.com',
    info: '原项目标注经常更换域名、出现 Cloudflare，失效后不再维护。',
    health: SourceHealth.noLongerUpdated,
    message: '不再维护，Flutter 版仅保留入口。',
  ),
  MediaSource(
    id: 'yjys',
    index: 10,
    name: '雪落影视',
    kind: SourceKind.movies,
    defaultDomain: 'https://xl02.com.de',
    info: '质量高，无广告但更新随缘。',
    health: SourceHealth.abnormal,
    message: '原项目标注搜索和部分接口存在验证，Flutter 版不实现绕过验证。',
  ),
  MediaSource(
    id: 'xbyy',
    index: 11,
    name: '小宝影院',
    kind: SourceKind.movies,
    defaultDomain: 'https://xiaoxintv.cc',
    info: '质量不错，原项目标注可能需要代理。',
    health: SourceHealth.abnormal,
  ),
  MediaSource(
    id: 'nyyy',
    index: 12,
    name: '纽约影院',
    kind: SourceKind.movies,
    defaultDomain: 'https://nycvod.com',
    info: '质量不错，请勿相信视频中的博彩广告。',
    health: SourceHealth.abnormal,
    message: '原项目标注搜索偶尔存在服务器验证或返回空数据。',
  ),
  MediaSource(
    id: 'girigirilove',
    index: 16,
    name: 'ギリギリ愛',
    kind: SourceKind.anime,
    defaultDomain: 'https://ani.girigirilove.com',
    releasePage: 'https://girigirilove.top/',
    info: '质量高，无国产动漫。',
    health: SourceHealth.abnormal,
    message: '首页、分类、详情和公开播放已适配；搜索页可能出现站点验证，Flutter 版不做绕过。',
  ),
];

MediaSource sourceById(String id) {
  return sourceCatalog.firstWhere(
    (source) => source.id == id,
    orElse: () => sourceCatalog.firstWhere((source) => source.id == 'zxzj'),
  );
}
